const items = [
    {
    id: 1,
    name: "Nevera No Frost 360 Lts",
    price: 2040800,
    quantitu: 1,
    url: "1.jpeg",
    deleted: false,
    },
    {
    id: 2,
    nombre: "Televisor OLED 55''",
    precio: 4499900,
    cantidad: 1,
    url: "2.jpeg",
    deleted: false,
    },
    {
    id: 3,
    nombre: "Escritorio Ajustable Modulart",
    precio: 899990,
    cantidad: 1,
    url: "3.jpeg",
    deleted: false,
    },
    {
    id: 4,
    nombre: "Poltrona Gunnared",
    precio: 1199990,
    cantidad: 1,
    url: "4.jpeg",
    deleted: false,
    },
    {
    id: 5,
    nombre: "Audífonos Inalámbricos WH-1000XM5",
    precio: 1249900,
    cantidad: 1,
    url: "5.jpeg",
    deleted: false,
    },
    {
    id: 6,
    nombre: "Bicicleta de Montaña Marlin 7",
    precio: 2499900,
    cantidad: 1,
    url: "6.jpeg",
    deleted: false,
    },
    {
    id: 7,
    nombre: "Nintendo Switch V2 + Joy-Con",
    precio: 1014035,
    cantidad: 1,
    url: "7.jpeg",
    deleted: false,
    },
    {
    id: 8,
    nombre: "Apple Watch Series 8",
    precio: 2149900,
    cantidad: 1,
    url: "8.jpeg",
    deleted: false,
    },
    {
    id: 9,
    nombre: "El Juego del Ángel - Carlos Ruiz Zafón",
    precio: 64900,
    cantidad: 1,
    url: "9.jpeg",
    deleted: false,
    },
    {
    id: 10,
    nombre: "Linterna LED Multifunción 3X1",
    precio: 179900,
    cantidad: 1,
    url: "10.jpeg",
    deleted: false,
    },
    {
    id: 11,
    nombre: "Cafetera Espresso Manual De'Longhi",
    precio: 799900,
    cantidad: 1,
    url: "11.jpeg",
    deleted: false,
    },
    {
    id: 12,
    nombre: "Monitor UltraSharp 27''",
    precio: 1499900,
    cantidad: 1,
    url: "12.jpeg",
    deleted: false,
    },
    {
    id: 13,
    nombre: "Camiseta Selección Colombia",
    precio: 349950,
    cantidad: 1,
    url: "13.jpeg",
    deleted: false,
    },
    {
    id: 14,
    nombre: "Cámara EOS M50",
    precio: 2399900,
    cantidad: 1,
    url: "14.jpeg",
    deleted: false,
    },
    {
    id: 15,
    nombre: "Aspiradora Inalámbrica V11",
    precio: 2899900,
    cantidad: 1,
    url: "15.jpeg",
    deleted: false,
    },
    {
    id: 16,
    nombre: "El Libro de Bill - Alex Hirsch",
    precio: 38400,
    cantidad: 1,
    url: "16.jpeg",
    deleted: false,
    },
    {
    id: 17,
    nombre: "Reloj G-Shock",
    precio: 599900,
    cantidad: 1,
    url: "17.jpeg",
    deleted: false,
    },
    {
    id: 18,
    nombre: "Mochila SuperBreak",
    precio: 149900,
    cantidad: 1,
    url: "18.jpeg",
    deleted: false,
    }
]